---
title: "species.compare"
author: "daniellembecker"
date: "2023-07-21"
output: html_document
---

Use the Bray-Curtis Dissimilarity to measure the dissimilarity between two tretament groups with differing species of Pocillopora grandis and Pocillopora meandrina

#load libraries
```{r}
library("tidyverse")
library("dplyr")
library("vegan")
```

#load dataframe of species distribution in treatments
```{r}
species <- read.csv("RAnalysis/Data/species.compare/species.distribution.csv")
```

```{r}
# Run a PERMANOVA

#Parametric test for differences between independent groups for multiple continuous dependent variables.
species.matrix<- as.matrix(species[,2:3]) # select response variables for matrix

#Quantify pairwise compositional dissimilarity between sites based on species occurrences using Bray-Curtis dissimilarity, abundance weighted 
species.dist<-vegdist(species.matrix, method='bray')
species.dist #0.0625, sites are close to identical

#PERMANOVA
species.div<-adonis2(species.dist~as.factor(species$treatment), data=species, permutations=9999)
species.div

#?? 'nperm' >= set of all permutations: complete enumeration.
#Set of permutations < 'minperm'. Generating entire set.

```


