---
title: "METH_GE_COMPARE"
author: "Danielle M. Becker"
date: "20220720"
output: html_document
---

#### Gene Expression and DNA Methylation comparison ####
## Used to compare general relationship between DNA methylation and gene expression
## Code developed from Javier A Rodriguez-Casariego paper: https://onlinelibrary.wiley.com/doi/pdf/10.1111/mec.16246?casa_token=DGoNlwKZByAAAAAA:i6JDcylh98txNEMQnr6dUTFxKd1sX7xotbSMZJq-DDOyqZGUPHObc30PhaWOAqpEufHMcJJ_wlQbQvbG
## https://github.com/jarcasariego/ACER_clonal_divergence/blob/main/GE_GbM_association/rmd/GE_DNAm_control.Rmd

```{r load packages}

## load packages
library(rtracklayer) # on bioconducter
library(dplyr)
library(edgeR)
library(factoextra)
library(cowplot)
library(wesanderson)
library(viridis)
library(adegenet)
library(ggplot2)
library(matrixStats)
library(grid)
library(gridExtra)
library(RColorBrewer)
library(stringr)
library(tidyverse)
pal <- brewer.pal(n = 3, name = "PRGn")
```

#### Functions ####
```{r}
# Function for subset 'mat' for the target expression,DNA methylation, and gene attributes modified from @adowneywall
subMat_control <- function(x){
  y <- data.frame(gene_length=log2(x$gene_length),
                  exon=log2(x$exon_count),totalCpG=log2(x$all_count),
                  Methylation=x$mean_Cc,Methylation_CV=x$cv_Cc,
                  Gene_Expression=x$gene_mean_Cc,Gene_Expression_CV=x$gene_cv_Cc)
  return(y)
}
get_density <- function(x, y, ...) {
  dens <- MASS::kde2d(x, y, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}
perCentCpGCoverage <- function(x){sum(c(mat$cov5_count/mat$all_count)*100 > x)}
# Function for generating three panel contribution plot for the different PCs
suppContriFig <- function(x){
  temp <- list()
  for(i in 1:3){
    temp[[i]] <- fviz_contrib(x, choice = "var", axes = i, top = 10,color = "black",fill = "grey",
                              sort.val = "none")
  }
  return(temp)
}
```

Load metadata
```{r}
#### Data ####
# Read in metadata
meta.data <- read.csv("RAnalysis/Data/RNA-seq/metadata.RNAseq.csv", header=T, sep=",", na.string="NA", stringsAsFactors = F) #read in info
colnames(meta.data) <- c("colonyID","treatment","block","Sample_ID")
ID <- meta.data$Sample_ID
```

Processing expression data
```{r}
counts <- read.csv("RAnalysis/Data/RNA-seq/Poc_gene_count_matrix.csv", header = TRUE, row.names = 1) #read in genes count matrix
colnames(counts) <- str_sub(colnames(counts), 1, 3) #remove everything after the first _ to just have the sample names
# Order columns by sample name
colnames(counts) <- c("C17","C18","C19","C20","C21","C22","C23","C24","C25","C26","C27","C28","C29","C30","C31","C32","E10","E11","E12","E13","E14","E15","E16","E1","E2","E3", "E4", "E5", "E6", "E7", "E8", "E9")
counts <- counts[, colnames(counts) %in% ID] #intersect with ID to maintain only samples a
counts <- counts[, order(colnames(counts))]
dge_gene <- DGEList(counts,genes = rownames(counts))
saveRDS(dge_gene, "RAnalysis/Data/GE_meth_compare/RNA_gene_preNormalization_DGEListObj.Rdata")
```


```{r}
# Methylation Summary Table
# load gene reference file - this contains the chromosome and starting gene coordinate (used to uniquely identify genes in the CpG file) and the gene_id which will be used to merge the expression and CpG data. I created this before and saved it as gene_GeneLoc.RData
#ref <- readRDS("../WGBS/data/gene_GeneLoc.RData")

#SAMPLES E2, E16, AND C19 WERE EXCLUDED DUE TO DEDUPLICATION AND LOW COUNTS
# Read in gene methylation data
gene_dnam <- readRDS("RAnalysis/Output/WGBS/sample_all_methylated_data_5x.Rdata") #read in info


#rename sample.ID to include corresponding E and C in front for enriched and control for later analysis
gene_dnam <- gene_dnam %>%
    mutate(Sample.ID = recode(Sample.ID, '1' = 'E1', '3' = 'E3', '4' = 'E4', '5' = 'E5', '6' = 'E6', '7' = 'E7', '8' = 'E8', '9' = 'E9','10' = 'E10', '11' = 'E11', '12' = 'E12','13' = 'E13', '14' = 'E14', '15' = 'E15', '16' = 'E16', '17' = 'C17', '18' = 'C18', '20' = 'C20', '21' = 'C21', '22' = 'C22', '23' = 'C23', '24' = 'C24', '25' = 'C25', '26' = 'C26', '27' = 'C27', '28' = 'C28', '29' = 'C29', '30' = 'C30', '31' = 'C31', '32' = 'C32'))


#check to see all where renamed correctly
unique(gene_dnam$Sample.ID)

#change from long to wide format
meth <- data.frame (gene_dnam %>%
                   group_by(Sample.ID, gene) %>%
                   summarise(mean = mean(per.meth), n = n()) %>%
                   spread(., key = Sample.ID, value = mean))

#filter for a min 3 Cpg per gene
meth <- meth[which(meth$n > 2),]
cpg10xgene <- meth[,1:2]  
colnames(cpg10xgene) <- c("gene_id", "cov10_count")
rownames(meth) <- meth$gene
meth <- meth[,-1]
meth <- as.matrix(meth)
meth <- meth/100
saveRDS(meth, "RAnalysis/Data/GE_meth_compare/meth_dataset.RData")

## Create a summary of methylation for each gene ##
mean_meth <- rowMeans(meth)

# create list for sample IDs from metadata and select from that list with filtering, pipe, row means
list_E <- filter(meta.data, treatment == "enriched") #filter only enriched data from metadata

list_C <- filter(meta.data, treatment == "control") #filter only control data from metadata

list_E <- as.list(list_E$Sample_ID) #make list of just enriched IDs

list_C <- as.list(list_C$Sample_ID) #make list of just control IDs
  
# mean gene meth enriched 
subset_meth_E <- meth[, colnames(meth)%in%list_E] #subset data from main m matrix for just enriched data

mean_meth_E <- rowMeans(subset_meth_E)

# Mean gene meth control
subset_meth_C <- meth[, colnames(meth)%in%list_C] #subset data from main m matrix for just control data

mean_meth_C <- rowMeans(subset_meth_C)

# Coefficient of Variation for enriched samples
sd_meth_E <- rowSds(subset_meth_E)
cv_meth_E <- sd_meth_E/mean_meth_E
 
# Coefficient of Variation for control
sd_meth_C <- rowSds(subset_meth_C)
cv_meth_C <- sd_meth_C/mean_meth_C

# Coefficient of Variation among treatments
meanAmongTrt_meth <- cbind(mean_meth_E,mean_meth_C)
sd_meanAmongTrt_meth <- rowSds(meanAmongTrt_meth)
mean_meanAmongTrt_meth <- rowMeans(meanAmongTrt_meth)
cv_mean_AmongTrt_meth <- sd_meanAmongTrt_meth/mean_meanAmongTrt_meth

# Difference in gene methylation between treatments
diff_Trt_meth <- mean_meth_E-mean_meth_C

# Creat matrix of all CpG summary stats
meth_summary <- cbind(mean_meth,mean_meth_E,mean_meth_C,cv_meth_E,cv_meth_C,cv_mean_AmongTrt_meth,
                      diff_Trt_meth) # bind all data frames with summary stats
meth_summary[is.na(meth_summary)]<-0 #filter for all methylation data over 0
meth_summary <- data.frame(gene_id = rownames(meth_summary),meth_summary) #change gene ID column name
meth_annot <- left_join(cpg10xgene, meth_summary) #join Cpg and meth summary
#meth_annot$label <- paste0(meth_annot$chr,"_",meth_annot$start,"_",meth_annot$stop)
#meth_reduce <- data.frame(label=meth_annot$label,meth_annot[,1:9])


#### Summarize the gene expression data ####

expression <- dge_gene$counts
subset_expression <- expression[, colnames(expression)%in%list_E] 
subset_expression <- subset_expression[rowSums(subset_expression[])>0,]
expression <- expression[rownames(expression) %in% rownames(subset_expression),]
expression_cpm_log <- log2(cpm(expression)+ 1) # log2 cpm transformation
expression <- expression_cpm_log

# Mean gene expression all samples
mean_express <- rowMeans(expression)

# mean gene expression enriched 
subset_express_E <- expression[, colnames(expression)%in%list_E] #subset data from main m matrix for just enriched data

mean_express_E <- rowMeans(subset_express_E) #take mean per gene ID

# Mean gene expression control
subset_express_C <- expression[, colnames(expression)%in%list_C] #subset data from main m matrix for just control data

mean_express_C <- rowMeans(subset_express_C) #take mean per gene ID

# Coefficient of Variation for enriched gene expression
sd_express_E <- rowSds(subset_express_E)
cv_express_E <- sd_express_E/mean_express_E

# Coefficient of Variation for control gene expression
sd_express_C <- rowSds(subset_express_C)
cv_express_C <- sd_express_C/mean_express_C

# Coefficient of Variation among treatments
meanAmongTrt_express <- cbind(mean_express_E,mean_express_C)
sd_meanAmongTrt_express <- rowSds(meanAmongTrt_express)
mean_meanAmongTrt_express <- rowMeans(meanAmongTrt_express)
cv_mean_AmongTrt_express <- sd_meanAmongTrt_express/mean_meanAmongTrt_express

# Difference in gene expression between Trt
diff_Trt_express <- mean_express_E-mean_express_C

# Create matrix of all gene expression summary stats
gene_summary <- cbind(mean_express,mean_express_E,mean_express_C,cv_express_E,cv_express_C,cv_mean_AmongTrt_express,
                      diff_Trt_express)
gene_summary[is.na(gene_summary)]<-0
colnames(gene_summary) <- paste0("gene_",colnames(gene_summary))
gene_summary <- data.frame(gene_id = rownames(gene_summary),gene_summary)

# transcriptomic data
transcriptomic <- read.csv("RAnalysis/Genome/GFF3.csv") #load annotation GFF3 file

#remove first three columns in data frame
transcriptomic <- transcriptomic[,-(1:3),drop=FALSE]
transcriptomic <- transcriptomic[,-(4:6),drop=FALSE]

#add gene between Pver_g to match gene_summary
transcriptomic$gene_id <-  gsub("Pver_g","Pver_gene_g", transcriptomic$gene_id)

gene_annot <- left_join(gene_summary, transcriptomic)
#gene_annot <- left_join(gene_annot, ref)
#gene_annot$label <- paste0(gene_annot$chr,"_",gene_annot$start,"_",gene_annot$stop)
#gene_reduce <- data.frame(label=gene_annot$label,gene_annot[,c(9,2:8)])
gene_annot <- gene_annot[,-(9:13),drop=FALSE]

# Combine gene expression, exon count and CpG (DNA mehtylation data)
gSum <- left_join(meth_annot, gene_annot)

# Reducing the data.frame to include places were we have all the data.
gSum_red<-gSum[!is.na(gSum$cov10_count),]
gSum_red<-gSum_red[!is.na(gSum_red$gene_mean_express),]

# Saving reduced data.frame
saveRDS(gSum,"RAnalysis/Data/GE_meth_compare/Multi_geneSummaryComplete.RData")

# Saving the reduced data.frame
saveRDS(gSum_red,"RAnalysis/Data/GE_meth_compare/Multi_geneSummaryReduced.RData")
```

```{r}
mat <- readRDS("RAnalysis/Data/GE_meth_compare/Multi_geneSummaryReduced.RData")

## Mean Methylation vs Gene Expression following Liew et al
df <- mat

#control log gene expression x % methylation
df$log_gene_C <- log(df$gene_mean_express_C+1)
df$per_meth_C <- df$mean_meth_C * 100

df$density <- get_density(df$gene_mean_express_C, df$mean_meth_C*100, n = 100)

ggplot(df,aes(x=per_meth_C,y=log_gene_C)) + 
    geom_point(aes(colour = density)) + ylim(0,2) + 
    geom_smooth(method=lm,colour="orange",size=2,na.rm = TRUE) +
    scale_color_viridis() +
    labs(x="DNA Methylation (%)", y = "log10 (mean expression +1)") +
    theme_cowplot()

#enriched log gene expression x % methylation
df$log_gene_E <- log(df$gene_mean_express_E+1)
df$per_meth_E <- df$mean_meth_E * 100

ggplot(df,aes(x=per_meth_E,y=log_gene_E)) + 
    geom_point() + ylim(0,2) + 
    geom_smooth(method=lm,colour="orange",size=2,na.rm = TRUE) +
    scale_color_viridis() +
    labs(x="DNA Methylation (%)", y = "log10 (mean expression +1)") +
    theme_cowplot()

## Mean Methylation vs Gene Expression following Javi et al

df$density <- get_density(df$gene_mean_express_E, df$mean_meth_E*100, n = 100)
mean_GbMvsGE_enriched <- ggplot(df,aes(x=gene_mean_express_E,y=mean_meth_E*100)) + 
    geom_point(aes(color = density)) + ylim(0,100) + 
    geom_smooth(method=lm,colour="orange",size=2,na.rm = TRUE) +
    scale_color_viridis() +
    labs(x="Gene Expression (log2-cpm)",y="DNA Methylation (%)") +
    theme_cowplot()

df$density <- get_density(df$gene_mean_express_C, df$mean_meth_C*100, n = 100)
mean_GbMvsGE_control <- ggplot(df,aes(x=gene_mean_express_C, y=mean_meth_C*100)) + 
    geom_point(aes(color = density)) + ylim(0,100) + 
    geom_smooth(method=lm,colour="orange",size=2,na.rm = TRUE) +
    scale_color_viridis() +
    labs(x="Gene Expression (log2-cpm)",y="DNA Methylation (%)") +
    theme_cowplot()

## Mean Methylation vs Gene Expression CV (log)
df$density <- get_density(log(df$gene_cv_express_E), df$mean_meth_E*100, n = 100)
meanGbMvsGEcv_enriched <- ggplot(df,aes(log(x=gene_cv_express_E),y=mean_meth_E*100)) + 
    geom_point(aes(color = density)) + ylim(0,100) + scale_color_viridis() +
    geom_smooth(method=lm,colour="orange",size=2) +
    labs(x=bquote("Gene Expression"~CV[Ind]~"(log)"),y="DNA Methylation (%)") +
    theme_cowplot()

df$density <- get_density(log(df$gene_cv_express_C+1), df$mean_meth_C*100, n = 100)
meanGbMvsGEcv_control <- ggplot(df,aes(log(x=gene_cv_express_C+1),y=mean_meth_C*100)) + 
    geom_point(aes(color = density)) + ylim(0,100) + scale_color_viridis() +
    geom_smooth(method=lm,colour="orange",size=2) +
    labs(x=bquote("Gene Expression"~CV[Ind]~"(log)"),y="DNA Methylation (%)") +
    theme_cowplot()

enriched_plots <- plot_grid(mean_GbMvsGE_enriched, meanGbMvsGEcv_enriched, labels=c("A", "B"),ncol=1)
control_plots <- plot_grid(mean_GbMvsGE_control, meanGbMvsGEcv_control, labels=c("C", "D"),ncol=1)

### Figure 5 ###
fig <- plot_grid(shallow_plots, deep_plots)
#ggsave(fig5,filename="results/figures/Figure5/Figure5.pdf")
ggsave(fig,filename="output/GbM_GE_correlation.png", height = 7, width = 9)
### Statistics ###
# Linear model with Mean gene DNA methylation as predictor 
# and Mean gene expression or CV as response  
# Mean Methylation vs. Mean Gene Expression
(cpg_ge <- summary(lm(mat$gene_mean~mat$mean)))
# Mean Methylation vs. CV Gene Expression
(cpg_cv <- summary(lm(mat$gene_cv_S~mat$mean_S)))
# Number of genes included
length(mat$mean_S)
```

Differential methylation/gene expression correlation

```{r}

#Subset DM/GE dataset
mat_red <- subset(mat,select=c("gene_id","diff_Trt_meth","gene_diff_Trt_express","gene_cv_express_E","gene_cv_express_C"))
mat_red[,2] <- mat_red[,2]*100 

#Create a diff_cv variable for all contrasts 
mat_red$diff.cv <- c(mat_red$gene_cv_express_E-mat_red$gene_cv_express_C)
mat_red$methylDirection <- ifelse(mat_red$diff_Trt < 0,
                                      "Hypomethylation",
                                      "Hypermethylation")
```

```{r Plot GE vs meth diff}
#### Gene Expression vs. DMG change ####
p1<-ggplot(mat_red,
           aes(x=diff_Trt_meth,y=gene_diff_Trt_express,colour=methylDirection)) + 
  geom_smooth(method=lm,colour="orange",size=2,na.rm = TRUE) +
  geom_point(size=3) + ylim(-2.5,2.5) + xlim(-11,11) +  
  theme_cowplot() +
  labs(y=bquote("Gene expression (FoldChange"~Log[2]~")"),x="Methylation change in DMGs (fraction difference)") +
  theme(plot.title = element_text(hjust=0.5), legend.position = "none")
p1
p2<-ggplot(mat_red,
           aes(x=diff_Trt_meth,y=diff.cv,colour=methylDirection)) + 
  geom_smooth(method=lm,colour="orange",size=2,na.rm = TRUE) +
  geom_point(size=3) + ylim(-4,4) + xlim(-11,11) +  
  theme_cowplot() +
  labs(y=bquote("Gene Expression"~CV[ind]~"difference"),x="Methylation change in DMGs (fraction difference)") +
  theme(plot.title = element_text(hjust=0.5), legend.position = "none")
p2
fig <- plot_grid(p1, p2)
ggsave(fig,filename="RAnalysis/Output/Final_Figures/DMG_GE_correlation.png", height = 4, width = 9)
```

```{r}
## Statistical Model ##
# DMG Methylation diff vs. Mean diff Gene Expression
(dmg_ge <- summary(lm(mat_red$gene_diff_Trt_express~mat_red$diff_Trt_meth)))

# DMG Methylation diff vs. CV diff Gene Expression
(dmg_cv <- summary(lm(mat_red$diff.cv~mat_red$diff_Trt_meth)))
plot(lm(mat_red$gene_diff_Trt_express~mat_red$diff_Trt_meth))
plot(lm(mat_red$diff.cv~mat_red$diff_Trt_meth))
```

```{r}
#### Gene level summary difference ####
mat_final <- mat
Ctrol_dnam_diff <- (mat_final$mean_Dc-mat_final$mean_Cc)*100
Heated_dnam_diff <- (mat_final$mean_Dh-mat_final$mean_Ch)*100
gene_summary <- data.frame(Ctrol_dnam=Ctrol_dnam_diff,
                           Ctrol_ge=Ctrol_ge_diff)
gene_summary$Ctrol_density <- get_density(gene_summary$Ctrol_ge, gene_summary$Ctrol_dnam, n = 100)
gene_summary$Heated_density <- get_density(gene_summary$Heated_ge, gene_summary$Heated_dnam, n = 100)
gene_summary$SymbC_density <- get_density(gene_summary$SymbC_ge, gene_summary$SymbC_dnam, n = 100)
gene_summary$SymbD_density <- get_density(gene_summary$SymbD_ge, gene_summary$SymbD_dnam, n = 100)
```

```{r}
#Plot
## Dc_Cc - Gene level summary difference
pG_1<-ggplot(gene_summary,
           aes(y=Ctrol_ge_diff,x=Ctrol_dnam)) + 
  geom_point(size=3,aes(color=Ctrol_density)) + 
  scale_color_viridis() + xlim(-20,20) + ylim(-5,5) +
  geom_smooth(method=lm,colour="orange",size=2,na.rm = TRUE) +
  theme_cowplot() + 
  labs(y=bquote("Gene expression (FoldChange"~Log[2]~")"),x="Mean gene methylation (difference %)",title="Dc.vs.Cc") +
  theme(plot.title = element_text(hjust=0.5))
pG_1
pG_1_nolab <- pG_1 + theme(axis.title = element_blank(),
                       legend.position = "none")

summary(lm(gene_summary$SymbD_ge~gene_summary$SymbD_dnam))
```

```{r}
#### Final Figure ####
plot1 <- plot_grid(p1_nolab,p2_nolab, p3_nolab,p4_nolab,ncol=4)
plot2 <- plot_grid(pG_1_nolab,pG_2_nolab,pG_3_nolab,pG_4_nolab,ncol=4)
x.grob1 <- textGrob("DMGs (difference %)", 
                    gp=gpar(col="black", fontsize=15))
x.grob2 <- textGrob("DNA Methylation (difference %)", 
                    gp=gpar(col="black", fontsize=15))
y.grob1 <- textGrob("Gene Expression (log2 fold change)", 
                    gp=gpar( col="black", fontsize=15), rot=90)
save1<-grid.arrange(arrangeGrob(plot1,bottom = x.grob1))
save2<-grid.arrange(arrangeGrob(plot2, bottom = x.grob2))
plot3<-plot_grid(save2,save1,nrow=2,labels=c("A","B"))
saveG<-grid.arrange(arrangeGrob(plot3, left = y.grob1))
ggsave(saveG,filename="output/Fig_9.png", height = 8, width = 13)
```